// Mocks generated by Mockito 5.4.6 from annotations
// in fsp_server/test/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i2;
import 'dart:math' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:postgres/src/client_messages.dart' as _i9;
import 'package:postgres/src/connection.dart' as _i4;
import 'package:postgres/src/execution_context.dart' as _i3;
import 'package:postgres/src/replication.dart' as _i6;
import 'package:postgres/src/server_messages.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncoding_0 extends _i1.SmartFake implements _i2.Encoding {
  _FakeEncoding_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgreSQLResult_1 extends _i1.SmartFake
    implements _i3.PostgreSQLResult {
  _FakePostgreSQLResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIterator_2<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgreSQLResultRow_3 extends _i1.SmartFake
    implements _i3.PostgreSQLResultRow {
  _FakePostgreSQLResultRow_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostgreSQLConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgreSQLConnection extends _i1.Mock
    implements _i4.PostgreSQLConnection {
  MockPostgreSQLConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#host)),
          )
          as String);

  @override
  int get port =>
      (super.noSuchMethod(Invocation.getter(#port), returnValue: 0) as int);

  @override
  String get databaseName =>
      (super.noSuchMethod(
            Invocation.getter(#databaseName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#databaseName),
            ),
          )
          as String);

  @override
  bool get useSSL =>
      (super.noSuchMethod(Invocation.getter(#useSSL), returnValue: false)
          as bool);

  @override
  int get timeoutInSeconds =>
      (super.noSuchMethod(Invocation.getter(#timeoutInSeconds), returnValue: 0)
          as int);

  @override
  int get queryTimeoutInSeconds =>
      (super.noSuchMethod(
            Invocation.getter(#queryTimeoutInSeconds),
            returnValue: 0,
          )
          as int);

  @override
  String get timeZone =>
      (super.noSuchMethod(
            Invocation.getter(#timeZone),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#timeZone),
            ),
          )
          as String);

  @override
  int get processID =>
      (super.noSuchMethod(Invocation.getter(#processID), returnValue: 0)
          as int);

  @override
  bool get isUnixSocket =>
      (super.noSuchMethod(Invocation.getter(#isUnixSocket), returnValue: false)
          as bool);

  @override
  bool get allowClearTextPassword =>
      (super.noSuchMethod(
            Invocation.getter(#allowClearTextPassword),
            returnValue: false,
          )
          as bool);

  @override
  _i6.ReplicationMode get replicationMode =>
      (super.noSuchMethod(
            Invocation.getter(#replicationMode),
            returnValue: _i6.ReplicationMode.physical,
          )
          as _i6.ReplicationMode);

  @override
  _i7.Stream<_i4.Notification> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _i7.Stream<_i4.Notification>.empty(),
          )
          as _i7.Stream<_i4.Notification>);

  @override
  _i7.Stream<_i8.ServerMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i7.Stream<_i8.ServerMessage>.empty(),
          )
          as _i7.Stream<_i8.ServerMessage>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  Map<String, String> get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.Encoding get encoding =>
      (super.noSuchMethod(
            Invocation.getter(#encoding),
            returnValue: _FakeEncoding_0(this, Invocation.getter(#encoding)),
          )
          as _i2.Encoding);

  @override
  int get queueSize =>
      (super.noSuchMethod(Invocation.getter(#queueSize), returnValue: 0)
          as int);

  @override
  _i7.Future<dynamic> open() =>
      (super.noSuchMethod(
            Invocation.method(#open, []),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  void addMessage(_i9.ClientMessage? message) => super.noSuchMethod(
    Invocation.method(#addMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<dynamic> transaction(
    _i7.Future<dynamic> Function(_i3.PostgreSQLExecutionContext)? queryBlock, {
    int? commitTimeoutInSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [queryBlock],
              {#commitTimeoutInSeconds: commitTimeoutInSeconds},
            ),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  void cancelTransaction({String? reason}) => super.noSuchMethod(
    Invocation.method(#cancelTransaction, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i3.PostgreSQLResult> query(
    String? fmtString, {
    Map<String, dynamic>? substitutionValues,
    bool? allowReuse,
    int? timeoutInSeconds,
    bool? useSimpleQueryProtocol,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [fmtString],
              {
                #substitutionValues: substitutionValues,
                #allowReuse: allowReuse,
                #timeoutInSeconds: timeoutInSeconds,
                #useSimpleQueryProtocol: useSimpleQueryProtocol,
              },
            ),
            returnValue: _i7.Future<_i3.PostgreSQLResult>.value(
              _FakePostgreSQLResult_1(
                this,
                Invocation.method(
                  #query,
                  [fmtString],
                  {
                    #substitutionValues: substitutionValues,
                    #allowReuse: allowReuse,
                    #timeoutInSeconds: timeoutInSeconds,
                    #useSimpleQueryProtocol: useSimpleQueryProtocol,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i3.PostgreSQLResult>);

  @override
  _i7.Future<List<Map<String, Map<String, dynamic>>>> mappedResultsQuery(
    String? fmtString, {
    Map<String, dynamic>? substitutionValues = const {},
    bool? allowReuse,
    int? timeoutInSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mappedResultsQuery,
              [fmtString],
              {
                #substitutionValues: substitutionValues,
                #allowReuse: allowReuse,
                #timeoutInSeconds: timeoutInSeconds,
              },
            ),
            returnValue:
                _i7.Future<List<Map<String, Map<String, dynamic>>>>.value(
                  <Map<String, Map<String, dynamic>>>[],
                ),
          )
          as _i7.Future<List<Map<String, Map<String, dynamic>>>>);

  @override
  _i7.Future<int> execute(
    String? fmtString, {
    Map<String, dynamic>? substitutionValues = const {},
    int? timeoutInSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #execute,
              [fmtString],
              {
                #substitutionValues: substitutionValues,
                #timeoutInSeconds: timeoutInSeconds,
              },
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}

/// A class which mocks [PostgreSQLResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgreSQLResult extends _i1.Mock implements _i3.PostgreSQLResult {
  MockPostgreSQLResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get affectedRowCount =>
      (super.noSuchMethod(Invocation.getter(#affectedRowCount), returnValue: 0)
          as int);

  @override
  List<_i3.ColumnDescription> get columnDescriptions =>
      (super.noSuchMethod(
            Invocation.getter(#columnDescriptions),
            returnValue: <_i3.ColumnDescription>[],
          )
          as List<_i3.ColumnDescription>);

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  Iterable<_i3.PostgreSQLResultRow> get reversed =>
      (super.noSuchMethod(
            Invocation.getter(#reversed),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  set first(_i3.PostgreSQLResultRow? value) => super.noSuchMethod(
    Invocation.setter(#first, value),
    returnValueForMissingStub: null,
  );

  @override
  set last(_i3.PostgreSQLResultRow? value) => super.noSuchMethod(
    Invocation.setter(#last, value),
    returnValueForMissingStub: null,
  );

  @override
  set length(int? newLength) => super.noSuchMethod(
    Invocation.setter(#length, newLength),
    returnValueForMissingStub: null,
  );

  @override
  Iterator<_i3.PostgreSQLResultRow> get iterator =>
      (super.noSuchMethod(
            Invocation.getter(#iterator),
            returnValue: _FakeIterator_2<_i3.PostgreSQLResultRow>(
              this,
              Invocation.getter(#iterator),
            ),
          )
          as Iterator<_i3.PostgreSQLResultRow>);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);

  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);

  @override
  _i3.PostgreSQLResultRow get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.getter(#first),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.getter(#last),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.getter(#single),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  List<R> cast<R>() =>
      (super.noSuchMethod(Invocation.method(#cast, []), returnValue: <R>[])
          as List<R>);

  @override
  _i3.PostgreSQLResultRow operator [](int? index) =>
      (super.noSuchMethod(
            Invocation.method(#[], [index]),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#[], [index]),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  void operator []=(int? index, _i3.PostgreSQLResultRow? value) =>
      super.noSuchMethod(
        Invocation.method(#[]=, [index, value]),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i3.PostgreSQLResultRow? value) => super.noSuchMethod(
    Invocation.method(#add, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void addAll(Iterable<_i3.PostgreSQLResultRow>? iterable) =>
      super.noSuchMethod(
        Invocation.method(#addAll, [iterable]),
        returnValueForMissingStub: null,
      );

  @override
  void sort([
    int Function(_i3.PostgreSQLResultRow, _i3.PostgreSQLResultRow)? compare,
  ]) => super.noSuchMethod(
    Invocation.method(#sort, [compare]),
    returnValueForMissingStub: null,
  );

  @override
  void shuffle([_i10.Random? random]) => super.noSuchMethod(
    Invocation.method(#shuffle, [random]),
    returnValueForMissingStub: null,
  );

  @override
  int indexOf(_i3.PostgreSQLResultRow? element, [int? start = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#indexOf, [element, start]),
            returnValue: 0,
          )
          as int);

  @override
  int indexWhere(
    bool Function(_i3.PostgreSQLResultRow)? test, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#indexWhere, [test, start]),
            returnValue: 0,
          )
          as int);

  @override
  int lastIndexWhere(
    bool Function(_i3.PostgreSQLResultRow)? test, [
    int? start,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#lastIndexWhere, [test, start]),
            returnValue: 0,
          )
          as int);

  @override
  int lastIndexOf(_i3.PostgreSQLResultRow? element, [int? start]) =>
      (super.noSuchMethod(
            Invocation.method(#lastIndexOf, [element, start]),
            returnValue: 0,
          )
          as int);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void insert(int? index, _i3.PostgreSQLResultRow? element) =>
      super.noSuchMethod(
        Invocation.method(#insert, [index, element]),
        returnValueForMissingStub: null,
      );

  @override
  void insertAll(int? index, Iterable<_i3.PostgreSQLResultRow>? iterable) =>
      super.noSuchMethod(
        Invocation.method(#insertAll, [index, iterable]),
        returnValueForMissingStub: null,
      );

  @override
  void setAll(int? index, Iterable<_i3.PostgreSQLResultRow>? iterable) =>
      super.noSuchMethod(
        Invocation.method(#setAll, [index, iterable]),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [value]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.PostgreSQLResultRow removeAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeAt, [index]),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#removeAt, [index]),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow removeLast() =>
      (super.noSuchMethod(
            Invocation.method(#removeLast, []),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#removeLast, []),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  void removeWhere(bool Function(_i3.PostgreSQLResultRow)? test) =>
      super.noSuchMethod(
        Invocation.method(#removeWhere, [test]),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i3.PostgreSQLResultRow)? test) =>
      super.noSuchMethod(
        Invocation.method(#retainWhere, [test]),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.PostgreSQLResultRow> operator +(
    List<_i3.PostgreSQLResultRow>? other,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#+, [other]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as List<_i3.PostgreSQLResultRow>);

  @override
  List<_i3.PostgreSQLResultRow> sublist(int? start, [int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#sublist, [start, end]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as List<_i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> getRange(int? start, int? end) =>
      (super.noSuchMethod(
            Invocation.method(#getRange, [start, end]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<_i3.PostgreSQLResultRow>? iterable, [
    int? skipCount = 0,
  ]) => super.noSuchMethod(
    Invocation.method(#setRange, [start, end, iterable, skipCount]),
    returnValueForMissingStub: null,
  );

  @override
  void removeRange(int? start, int? end) => super.noSuchMethod(
    Invocation.method(#removeRange, [start, end]),
    returnValueForMissingStub: null,
  );

  @override
  void fillRange(int? start, int? end, [_i3.PostgreSQLResultRow? fillValue]) =>
      super.noSuchMethod(
        Invocation.method(#fillRange, [start, end, fillValue]),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(
    int? start,
    int? end,
    Iterable<_i3.PostgreSQLResultRow>? replacements,
  ) => super.noSuchMethod(
    Invocation.method(#replaceRange, [start, end, replacements]),
    returnValueForMissingStub: null,
  );

  @override
  Map<int, _i3.PostgreSQLResultRow> asMap() =>
      (super.noSuchMethod(
            Invocation.method(#asMap, []),
            returnValue: <int, _i3.PostgreSQLResultRow>{},
          )
          as Map<int, _i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> followedBy(
    Iterable<_i3.PostgreSQLResultRow>? other,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#followedBy, [other]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  Iterable<T> map<T>(T Function(_i3.PostgreSQLResultRow)? toElement) =>
      (super.noSuchMethod(
            Invocation.method(#map, [toElement]),
            returnValue: <T>[],
          )
          as Iterable<T>);

  @override
  Iterable<_i3.PostgreSQLResultRow> where(
    bool Function(_i3.PostgreSQLResultRow)? test,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  Iterable<T> whereType<T>() =>
      (super.noSuchMethod(Invocation.method(#whereType, []), returnValue: <T>[])
          as Iterable<T>);

  @override
  Iterable<T> expand<T>(
    Iterable<T> Function(_i3.PostgreSQLResultRow)? toElements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [toElements]),
            returnValue: <T>[],
          )
          as Iterable<T>);

  @override
  bool contains(Object? element) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [element]),
            returnValue: false,
          )
          as bool);

  @override
  void forEach(void Function(_i3.PostgreSQLResultRow)? action) =>
      super.noSuchMethod(
        Invocation.method(#forEach, [action]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PostgreSQLResultRow reduce(
    _i3.PostgreSQLResultRow Function(
      _i3.PostgreSQLResultRow,
      _i3.PostgreSQLResultRow,
    )?
    combine,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#reduce, [combine]),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  T fold<T>(T? initialValue, T Function(T, _i3.PostgreSQLResultRow)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue: _i5.dummyValue<T>(
              this,
              Invocation.method(#fold, [initialValue, combine]),
            ),
          )
          as T);

  @override
  bool every(bool Function(_i3.PostgreSQLResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#every, [test]), returnValue: false)
          as bool);

  @override
  String join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#join, [separator]),
            ),
          )
          as String);

  @override
  bool any(bool Function(_i3.PostgreSQLResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#any, [test]), returnValue: false)
          as bool);

  @override
  List<_i3.PostgreSQLResultRow> toList({bool? growable = true}) =>
      (super.noSuchMethod(
            Invocation.method(#toList, [], {#growable: growable}),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as List<_i3.PostgreSQLResultRow>);

  @override
  Set<_i3.PostgreSQLResultRow> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: <_i3.PostgreSQLResultRow>{},
          )
          as Set<_i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> takeWhile(
    bool Function(_i3.PostgreSQLResultRow)? test,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  Iterable<_i3.PostgreSQLResultRow> skipWhile(
    bool Function(_i3.PostgreSQLResultRow)? test,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: <_i3.PostgreSQLResultRow>[],
          )
          as Iterable<_i3.PostgreSQLResultRow>);

  @override
  _i3.PostgreSQLResultRow firstWhere(
    bool Function(_i3.PostgreSQLResultRow)? test, {
    _i3.PostgreSQLResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow lastWhere(
    bool Function(_i3.PostgreSQLResultRow)? test, {
    _i3.PostgreSQLResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow singleWhere(
    bool Function(_i3.PostgreSQLResultRow)? test, {
    _i3.PostgreSQLResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            ),
          )
          as _i3.PostgreSQLResultRow);

  @override
  _i3.PostgreSQLResultRow elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue: _FakePostgreSQLResultRow_3(
              this,
              Invocation.method(#elementAt, [index]),
            ),
          )
          as _i3.PostgreSQLResultRow);
}

/// A class which mocks [PostgreSQLResultRow].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgreSQLResultRow extends _i1.Mock
    implements _i3.PostgreSQLResultRow {
  MockPostgreSQLResultRow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ColumnDescription> get columnDescriptions =>
      (super.noSuchMethod(
            Invocation.getter(#columnDescriptions),
            returnValue: <_i3.ColumnDescription>[],
          )
          as List<_i3.ColumnDescription>);

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  Iterable<dynamic> get reversed =>
      (super.noSuchMethod(
            Invocation.getter(#reversed),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  set first(dynamic value) => super.noSuchMethod(
    Invocation.setter(#first, value),
    returnValueForMissingStub: null,
  );

  @override
  set last(dynamic value) => super.noSuchMethod(
    Invocation.setter(#last, value),
    returnValueForMissingStub: null,
  );

  @override
  set length(int? newLength) => super.noSuchMethod(
    Invocation.setter(#length, newLength),
    returnValueForMissingStub: null,
  );

  @override
  Iterator<dynamic> get iterator =>
      (super.noSuchMethod(
            Invocation.getter(#iterator),
            returnValue: _FakeIterator_2<dynamic>(
              this,
              Invocation.getter(#iterator),
            ),
          )
          as Iterator<dynamic>);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);

  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);

  @override
  Map<String, Map<String, dynamic>> toTableColumnMap() =>
      (super.noSuchMethod(
            Invocation.method(#toTableColumnMap, []),
            returnValue: <String, Map<String, dynamic>>{},
          )
          as Map<String, Map<String, dynamic>>);

  @override
  Map<String, dynamic> toColumnMap() =>
      (super.noSuchMethod(
            Invocation.method(#toColumnMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<R> cast<R>() =>
      (super.noSuchMethod(Invocation.method(#cast, []), returnValue: <R>[])
          as List<R>);

  @override
  dynamic operator [](int? index) =>
      super.noSuchMethod(Invocation.method(#[], [index]));

  @override
  void operator []=(int? index, dynamic value) => super.noSuchMethod(
    Invocation.method(#[]=, [index, value]),
    returnValueForMissingStub: null,
  );

  @override
  void add(dynamic value) => super.noSuchMethod(
    Invocation.method(#add, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void addAll(Iterable<dynamic>? iterable) => super.noSuchMethod(
    Invocation.method(#addAll, [iterable]),
    returnValueForMissingStub: null,
  );

  @override
  void sort([int Function(dynamic, dynamic)? compare]) => super.noSuchMethod(
    Invocation.method(#sort, [compare]),
    returnValueForMissingStub: null,
  );

  @override
  void shuffle([_i10.Random? random]) => super.noSuchMethod(
    Invocation.method(#shuffle, [random]),
    returnValueForMissingStub: null,
  );

  @override
  int indexOf(dynamic element, [int? start = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#indexOf, [element, start]),
            returnValue: 0,
          )
          as int);

  @override
  int indexWhere(bool Function(dynamic)? test, [int? start = 0]) =>
      (super.noSuchMethod(
            Invocation.method(#indexWhere, [test, start]),
            returnValue: 0,
          )
          as int);

  @override
  int lastIndexWhere(bool Function(dynamic)? test, [int? start]) =>
      (super.noSuchMethod(
            Invocation.method(#lastIndexWhere, [test, start]),
            returnValue: 0,
          )
          as int);

  @override
  int lastIndexOf(dynamic element, [int? start]) =>
      (super.noSuchMethod(
            Invocation.method(#lastIndexOf, [element, start]),
            returnValue: 0,
          )
          as int);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void insert(int? index, dynamic element) => super.noSuchMethod(
    Invocation.method(#insert, [index, element]),
    returnValueForMissingStub: null,
  );

  @override
  void insertAll(int? index, Iterable<dynamic>? iterable) => super.noSuchMethod(
    Invocation.method(#insertAll, [index, iterable]),
    returnValueForMissingStub: null,
  );

  @override
  void setAll(int? index, Iterable<dynamic>? iterable) => super.noSuchMethod(
    Invocation.method(#setAll, [index, iterable]),
    returnValueForMissingStub: null,
  );

  @override
  bool remove(Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [value]),
            returnValue: false,
          )
          as bool);

  @override
  dynamic removeAt(int? index) =>
      super.noSuchMethod(Invocation.method(#removeAt, [index]));

  @override
  void removeWhere(bool Function(dynamic)? test) => super.noSuchMethod(
    Invocation.method(#removeWhere, [test]),
    returnValueForMissingStub: null,
  );

  @override
  void retainWhere(bool Function(dynamic)? test) => super.noSuchMethod(
    Invocation.method(#retainWhere, [test]),
    returnValueForMissingStub: null,
  );

  @override
  List<dynamic> operator +(List<dynamic>? other) =>
      (super.noSuchMethod(
            Invocation.method(#+, [other]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> sublist(int? start, [int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#sublist, [start, end]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Iterable<dynamic> getRange(int? start, int? end) =>
      (super.noSuchMethod(
            Invocation.method(#getRange, [start, end]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<dynamic>? iterable, [
    int? skipCount = 0,
  ]) => super.noSuchMethod(
    Invocation.method(#setRange, [start, end, iterable, skipCount]),
    returnValueForMissingStub: null,
  );

  @override
  void removeRange(int? start, int? end) => super.noSuchMethod(
    Invocation.method(#removeRange, [start, end]),
    returnValueForMissingStub: null,
  );

  @override
  void fillRange(int? start, int? end, [dynamic fillValue]) =>
      super.noSuchMethod(
        Invocation.method(#fillRange, [start, end, fillValue]),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(int? start, int? end, Iterable<dynamic>? replacements) =>
      super.noSuchMethod(
        Invocation.method(#replaceRange, [start, end, replacements]),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, dynamic> asMap() =>
      (super.noSuchMethod(
            Invocation.method(#asMap, []),
            returnValue: <int, dynamic>{},
          )
          as Map<int, dynamic>);

  @override
  Iterable<dynamic> followedBy(Iterable<dynamic>? other) =>
      (super.noSuchMethod(
            Invocation.method(#followedBy, [other]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  Iterable<T> map<T>(T Function(dynamic)? toElement) =>
      (super.noSuchMethod(
            Invocation.method(#map, [toElement]),
            returnValue: <T>[],
          )
          as Iterable<T>);

  @override
  Iterable<dynamic> where(bool Function(dynamic)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  Iterable<T> whereType<T>() =>
      (super.noSuchMethod(Invocation.method(#whereType, []), returnValue: <T>[])
          as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(dynamic)? toElements) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [toElements]),
            returnValue: <T>[],
          )
          as Iterable<T>);

  @override
  bool contains(Object? element) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [element]),
            returnValue: false,
          )
          as bool);

  @override
  void forEach(void Function(dynamic)? action) => super.noSuchMethod(
    Invocation.method(#forEach, [action]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic reduce(dynamic Function(dynamic, dynamic)? combine) =>
      super.noSuchMethod(Invocation.method(#reduce, [combine]));

  @override
  T fold<T>(T? initialValue, T Function(T, dynamic)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue: _i5.dummyValue<T>(
              this,
              Invocation.method(#fold, [initialValue, combine]),
            ),
          )
          as T);

  @override
  bool every(bool Function(dynamic)? test) =>
      (super.noSuchMethod(Invocation.method(#every, [test]), returnValue: false)
          as bool);

  @override
  String join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#join, [separator]),
            ),
          )
          as String);

  @override
  bool any(bool Function(dynamic)? test) =>
      (super.noSuchMethod(Invocation.method(#any, [test]), returnValue: false)
          as bool);

  @override
  List<dynamic> toList({bool? growable = true}) =>
      (super.noSuchMethod(
            Invocation.method(#toList, [], {#growable: growable}),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Set<dynamic> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: <dynamic>{},
          )
          as Set<dynamic>);

  @override
  Iterable<dynamic> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  Iterable<dynamic> takeWhile(bool Function(dynamic)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  Iterable<dynamic> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  Iterable<dynamic> skipWhile(bool Function(dynamic)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  dynamic firstWhere(
    bool Function(dynamic)? test, {
    dynamic Function()? orElse,
  }) => super.noSuchMethod(
    Invocation.method(#firstWhere, [test], {#orElse: orElse}),
  );

  @override
  dynamic lastWhere(
    bool Function(dynamic)? test, {
    dynamic Function()? orElse,
  }) => super.noSuchMethod(
    Invocation.method(#lastWhere, [test], {#orElse: orElse}),
  );

  @override
  dynamic singleWhere(
    bool Function(dynamic)? test, {
    dynamic Function()? orElse,
  }) => super.noSuchMethod(
    Invocation.method(#singleWhere, [test], {#orElse: orElse}),
  );

  @override
  dynamic elementAt(int? index) =>
      super.noSuchMethod(Invocation.method(#elementAt, [index]));
}
